# Generated by Django 5.2.14 on 2026-05-31 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_time_accuracy', models.CharField(choices=[('exact', 'Exact'), ('approximate', 'Approximate'), ('unknown', 'Unknown')], default='exact', max_length=32)),
                ('timezone_name', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChartCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_version', models.CharField(max_length=64)),
                ('ayanamsa', models.CharField(default='lahiri', max_length=64)),
                ('house_system', models.CharField(default='whole_sign', max_length=64)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='charts.birthprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DashaPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=64)),
                ('level', models.PositiveSmallIntegerField()),
                ('lord', models.CharField(max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dasha_periods', to='charts.chartcalculation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.dashaperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone_name', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['external_id'], name='charts_plac_externa_7f83f9_idx'), models.Index(fields=['name'], name='charts_plac_name_d996e5_idx')],
            },
        ),
        migrations.AddField(
            model_name='birthprofile',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charts.place'),
        ),
        migrations.CreateModel(
            name='PlanetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graha', models.CharField(max_length=32)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('rashi', models.CharField(max_length=32)),
                ('nakshatra', models.CharField(max_length=64)),
                ('pada', models.PositiveSmallIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_positions', to='charts.chartcalculation')),
            ],
        ),
        migrations.CreateModel(
            name='VargaPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varga', models.CharField(max_length=16)),
                ('graha', models.CharField(max_length=32)),
                ('rashi', models.CharField(max_length=32)),
                ('house', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varga_placements', to='charts.chartcalculation')),
            ],
        ),
        migrations.AddIndex(
            model_name='chartcalculation',
            index=models.Index(fields=['profile', 'created_at'], name='charts_char_profile_fb1f16_idx'),
        ),
        migrations.AddIndex(
            model_name='chartcalculation',
            index=models.Index(fields=['calculation_version'], name='charts_char_calcula_aa8570_idx'),
        ),
        migrations.AddIndex(
            model_name='chartcalculation',
            index=models.Index(fields=['status'], name='charts_char_status_660005_idx'),
        ),
        migrations.AddIndex(
            model_name='dashaperiod',
            index=models.Index(fields=['system', 'level'], name='charts_dash_system_e99c81_idx'),
        ),
        migrations.AddIndex(
            model_name='dashaperiod',
            index=models.Index(fields=['starts_at', 'ends_at'], name='charts_dash_starts__12d9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='birthprofile',
            index=models.Index(fields=['user', 'created_at'], name='charts_birt_user_id_36191f_idx'),
        ),
        migrations.AddIndex(
            model_name='birthprofile',
            index=models.Index(fields=['birth_date'], name='charts_birt_birth_d_73d1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='planetposition',
            index=models.Index(fields=['graha'], name='charts_plan_graha_f63137_idx'),
        ),
        migrations.AddIndex(
            model_name='planetposition',
            index=models.Index(fields=['rashi'], name='charts_plan_rashi_66de4e_idx'),
        ),
        migrations.AddIndex(
            model_name='planetposition',
            index=models.Index(fields=['nakshatra'], name='charts_plan_nakshat_af51c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planetposition',
            unique_together={('calculation', 'graha')},
        ),
        migrations.AddIndex(
            model_name='vargaplacement',
            index=models.Index(fields=['varga'], name='charts_varg_varga_21458e_idx'),
        ),
        migrations.AddIndex(
            model_name='vargaplacement',
            index=models.Index(fields=['graha'], name='charts_varg_graha_6ae521_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vargaplacement',
            unique_together={('calculation', 'varga', 'graha')},
        ),
    ]
