# Generated by Django 5.2.14 on 2026-06-11 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_birthprofile_calculation_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthProfileRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('partner', 'Partner'), ('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('boss', 'Boss'), ('subordinate', 'Subordinate'), ('opponent', 'Opponent'), ('other', 'Other')], default='partner', max_length=32)),
                ('link_status', models.CharField(choices=[('private', 'Private saved relation'), ('requested', 'User link requested'), ('accepted', 'User link accepted'), ('declined', 'User link declined'), ('blocked', 'User link blocked')], default='private', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='charts.birthprofile')),
                ('related_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='charts.birthprofile')),
                ('requested_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_profile_relationship_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_profile_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'role'], name='charts_birt_user_id_e0730a_idx'), models.Index(fields=['user', 'link_status'], name='charts_birt_user_id_87cf77_idx'), models.Index(fields=['requested_user', 'link_status'], name='charts_birt_request_2c7c5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'profile', 'related_profile'), name='unique_birth_profile_relationship'), models.CheckConstraint(condition=models.Q(('profile', models.F('related_profile')), _negated=True), name='birth_profile_relationship_not_self')],
            },
        ),
    ]
