# Generated by Django 5.2.14 on 2026-06-13 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_birthprofilerelationship_role_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='birthprofilerelationship',
            index=models.Index(fields=['user', 'updated_at'], name='charts_rel_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='birthprofilerelationship',
            index=models.Index(fields=['requested_user', 'link_status', 'updated_at'], name='charts_rel_inbox_updated_idx'),
        ),
    ]
