# Generated by Django 5.2.14 on 2026-06-18 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_birthprofile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type_id', models.CharField(max_length=64)),
                ('role_a_id', models.CharField(max_length=64)),
                ('role_b_id', models.CharField(max_length=64)),
                ('pair_key', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_relationships_as_a', to='charts.birthprofile')),
                ('chart_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_relationships_as_b', to='charts.birthprofile')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner_user', 'updated_at'], name='charts_chartrel_owner_upd_idx'), models.Index(fields=['owner_user', 'relationship_type_id'], name='charts_chartrel_owner_type_idx'), models.Index(fields=['owner_user', 'pair_key'], name='charts_chartrel_owner_pair_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_user', 'relationship_type_id', 'pair_key'), name='unique_chart_relationship_owner_type_pair'), models.CheckConstraint(condition=models.Q(('chart_a', models.F('chart_b')), _negated=True), name='chart_relationship_not_self')],
            },
        ),
    ]
