# Generated by Django 5.2.14 on 2026-05-31 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source_class', models.CharField(choices=[('canonical_prabhupada', 'Canonical Prabhupada'), ('canonical_gaudiya', 'Canonical Gaudiya'), ('jyotish_shastra', 'Jyotish shastra'), ('teacher_reference', 'Teacher reference'), ('research_only', 'Research only')], max_length=64)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(default='en', max_length=16)),
                ('source_url', models.URLField(blank=True)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('research_only', 'Research only'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='draft', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourcePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('language_code', models.CharField(default='en', max_length=16)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('research_only', 'Research only'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='draft', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='sources.sourcework')),
            ],
        ),
        migrations.CreateModel(
            name='VLCitationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_work_id', models.BigIntegerField(blank=True, null=True)),
                ('vl_text_unit_id', models.BigIntegerField(blank=True, null=True)),
                ('vl_text_id', models.BigIntegerField(blank=True, null=True)),
                ('public_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vl_links', to='sources.sourcepassage')),
            ],
        ),
        migrations.AddIndex(
            model_name='sourcepassage',
            index=models.Index(fields=['review_status'], name='sources_sou_review__957245_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcepassage',
            index=models.Index(fields=['reference'], name='sources_sou_referen_9051a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcepassage',
            unique_together={('work', 'reference', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='vlcitationlink',
            index=models.Index(fields=['vl_work_id'], name='sources_vlc_vl_work_d9003a_idx'),
        ),
        migrations.AddIndex(
            model_name='vlcitationlink',
            index=models.Index(fields=['vl_text_unit_id'], name='sources_vlc_vl_text_5f7814_idx'),
        ),
        migrations.AddIndex(
            model_name='vlcitationlink',
            index=models.Index(fields=['vl_text_id'], name='sources_vlc_vl_text_8bcd47_idx'),
        ),
    ]
