# Generated by Django 5.2.14 on 2026-05-31 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('condition', models.JSONField(default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('research_only', 'Research only'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='draft', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passages', models.ManyToManyField(blank=True, to='sources.sourcepassage')),
            ],
            options={
                'ordering': ['priority', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='InterpretationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('language_code', models.CharField(default='en', max_length=16)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('research_only', 'Research only'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='draft', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='interpretations.interpretationrule')),
            ],
        ),
        migrations.CreateModel(
            name='RemedyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('classical_trigger', models.CharField(max_length=255)),
                ('blocked_advice', models.TextField(blank=True)),
                ('vaishnava_reframe', models.TextField()),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('research_only', 'Research only'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='draft', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passages', models.ManyToManyField(blank=True, to='sources.sourcepassage')),
            ],
            options={
                'verbose_name_plural': 'remedy policies',
            },
        ),
        migrations.AddIndex(
            model_name='interpretationrule',
            index=models.Index(fields=['review_status', 'priority'], name='interpretat_review__c66a70_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretationblock',
            index=models.Index(fields=['section', 'language_code'], name='interpretat_section_b09913_idx'),
        ),
        migrations.AddIndex(
            model_name='interpretationblock',
            index=models.Index(fields=['review_status'], name='interpretat_review__68fe25_idx'),
        ),
        migrations.AddIndex(
            model_name='remedypolicy',
            index=models.Index(fields=['review_status'], name='interpretat_review__dec234_idx'),
        ),
    ]
