# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interpretations", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShastraConditionEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("condition_key", models.SlugField(max_length=180)),
                ("condition_kind", models.CharField(max_length=64)),
                ("condition_title", models.CharField(max_length=255)),
                ("score", models.PositiveIntegerField(default=0)),
                ("inferred_reference", models.CharField(blank=True, max_length=255)),
                ("reference_status", models.CharField(default="needs_review", max_length=64)),
                ("public_quote_policy", models.CharField(default="blocked_until_approved", max_length=64)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("research_only", "Research only"),
                            ("approved", "Approved"),
                            ("blocked", "Blocked"),
                        ],
                        default="research_only",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "passage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_evidence",
                        to="sources.sourcepassage",
                    ),
                ),
            ],
            options={
                "ordering": ["condition_key", "-score", "id"],
                "unique_together": {("condition_key", "passage")},
            },
        ),
        migrations.AddIndex(
            model_name="shastraconditionevidence",
            index=models.Index(fields=["condition_key", "-score"], name="interpretat_conditi_a1ae42_idx"),
        ),
        migrations.AddIndex(
            model_name="shastraconditionevidence",
            index=models.Index(fields=["review_status"], name="interpretat_review__8d02d0_idx"),
        ),
        migrations.AddIndex(
            model_name="shastraconditionevidence",
            index=models.Index(fields=["reference_status"], name="interpretat_referen_5b51ca_idx"),
        ),
    ]
