from django.urls import path

from .views import (
    BirthAnalysisPacketView,
    BirthCodexAnalysisChatView,
    BirthCodexAnalysisView,
    BirthDeepseekAnalysisView,
    BirthDraftAnalysisView,
    BirthQwenAnalysisView,
    BirthReportView,
    CompatibilityAnalysisPacketView,
    CompatibilityCodexAnalysisChatView,
    CompatibilityCodexAnalysisView,
    ShastraConditionMatrixView,
    ShastraEvidenceApproveView,
    ShastraEvidenceView,
)

urlpatterns = [
    path("reports/birth-chart", BirthReportView.as_view(), name="birth-report"),
    path(
        "reports/birth-chart/analysis-packet",
        BirthAnalysisPacketView.as_view(),
        name="birth-analysis-packet",
    ),
    path(
        "reports/birth-chart/draft-analysis",
        BirthDraftAnalysisView.as_view(),
        name="birth-draft-analysis",
    ),
    path(
        "reports/birth-chart/codex-analysis",
        BirthCodexAnalysisView.as_view(),
        name="birth-codex-analysis",
    ),
    path(
        "reports/birth-chart/qwen-analysis",
        BirthQwenAnalysisView.as_view(),
        name="birth-qwen-analysis",
    ),
    path(
        "reports/birth-chart/deepseek-analysis",
        BirthDeepseekAnalysisView.as_view(),
        name="birth-deepseek-analysis",
    ),
    path(
        "reports/birth-chart/codex-analysis/chat",
        BirthCodexAnalysisChatView.as_view(),
        name="birth-codex-analysis-chat",
    ),
    path(
        "reports/compatibility/analysis-packet",
        CompatibilityAnalysisPacketView.as_view(),
        name="compatibility-analysis-packet",
    ),
    path(
        "reports/compatibility/codex-analysis",
        CompatibilityCodexAnalysisView.as_view(),
        name="compatibility-codex-analysis",
    ),
    path(
        "reports/compatibility/codex-analysis/chat",
        CompatibilityCodexAnalysisChatView.as_view(),
        name="compatibility-codex-analysis-chat",
    ),
    path(
        "reports/shastra-condition-matrix",
        ShastraConditionMatrixView.as_view(),
        name="shastra-condition-matrix",
    ),
    path(
        "reports/shastra-evidence",
        ShastraEvidenceView.as_view(),
        name="shastra-evidence",
    ),
    path(
        "reports/shastra-evidence/<int:evidence_id>/approve",
        ShastraEvidenceApproveView.as_view(),
        name="shastra-evidence-approve",
    ),
]
