# Generated by Django 5.2.14 on 2026-06-13 04:30

from django.db import migrations, models


def backfill_preview_fields(apps, schema_editor):
    GeneratedAnalysisDraft = apps.get_model("reports", "GeneratedAnalysisDraft")
    updates = []
    for record in GeneratedAnalysisDraft.objects.only("id", "kind", "output_json").iterator(chunk_size=200):
        output = record.output_json if isinstance(record.output_json, dict) else {}
        sections = output.get("sections") if isinstance(output.get("sections"), list) else []
        first_section = sections[0] if sections and isinstance(sections[0], dict) else {}
        record.engine_label = str(output.get("engine_label") or "")[:160]
        record.section_count = len(sections)
        record.first_section_title = str(first_section.get("title") or "")[:240]
        if first_section:
            record.excerpt = str(first_section.get("body") or "")[:720]
        elif str(record.kind).endswith("_chat"):
            record.excerpt = str(output.get("answer") or "")[:720]
        else:
            record.excerpt = ""
        updates.append(record)
        if len(updates) >= 200:
            GeneratedAnalysisDraft.objects.bulk_update(
                updates,
                ["engine_label", "section_count", "first_section_title", "excerpt"],
            )
            updates = []
    if updates:
        GeneratedAnalysisDraft.objects.bulk_update(
            updates,
            ["engine_label", "section_count", "first_section_title", "excerpt"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_generatedanalysisdraft_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedanalysisdraft',
            name='engine_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='generatedanalysisdraft',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedanalysisdraft',
            name='first_section_title',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='generatedanalysisdraft',
            name='section_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_preview_fields, migrations.RunPython.noop),
    ]
