# Generated by Django 5.2.14 on 2026-06-13 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CHAT_ANALYSIS_KINDS = {
    "birth_chart_codex_cli_chat",
    "compatibility_codex_cli_chat",
    "current_day_transit_overview_chat",
}


def backfill_parent_analysis(apps, schema_editor):
    GeneratedAnalysisDraft = apps.get_model("reports", "GeneratedAnalysisDraft")
    updates = []
    for record in (
        GeneratedAnalysisDraft.objects.filter(kind__in=CHAT_ANALYSIS_KINDS, parent_analysis__isnull=True)
        .only("id", "input_snapshot")
        .iterator(chunk_size=500)
    ):
        snapshot = record.input_snapshot if isinstance(record.input_snapshot, dict) else {}
        analysis_id = snapshot.get("analysis_id")
        try:
            parent_id = int(analysis_id)
        except (TypeError, ValueError):
            continue
        if not GeneratedAnalysisDraft.objects.filter(id=parent_id).exists():
            continue
        record.parent_analysis_id = parent_id
        updates.append(record)
        if len(updates) >= 500:
            GeneratedAnalysisDraft.objects.bulk_update(updates, ["parent_analysis"])
            updates = []
    if updates:
        GeneratedAnalysisDraft.objects.bulk_update(updates, ["parent_analysis"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_generatedanalysisdraft_engine_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedanalysisdraft',
            name='parent_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_records', to='reports.generatedanalysisdraft'),
        ),
        migrations.RunPython(backfill_parent_analysis, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='generatedanalysisdraft',
            index=models.Index(fields=['parent_analysis', 'user', 'created_at'], name='reports_gen_parent_chat_idx'),
        ),
    ]
