# Generated by Django 5.2.14 on 2026-06-13 07:09

import django.db.models.deletion
from django.db import migrations, models


def profile_links_from_snapshot(snapshot):
    if not isinstance(snapshot, dict):
        return []
    links = []

    def add(value, role):
        try:
            profile_id = int(str(value))
        except (TypeError, ValueError):
            return
        if profile_id <= 0:
            return
        item = (profile_id, role)
        if item not in links:
            links.append(item)

    add(snapshot.get("profile_id"), "primary")
    for key in ("person_a", "person_b"):
        person = snapshot.get(key)
        if isinstance(person, dict):
            add(person.get("profile_id"), key)
    related_ids = snapshot.get("related_profile_ids")
    if isinstance(related_ids, list):
        for related_id in related_ids:
            add(related_id, "related")
    related_context = snapshot.get("related_profile_context")
    if isinstance(related_context, list):
        for item in related_context:
            profile = item.get("profile") if isinstance(item, dict) else None
            if isinstance(profile, dict):
                add(profile.get("id"), "related")
    return links


def backfill_profile_links(apps, schema_editor):
    GeneratedAnalysisDraft = apps.get_model("reports", "GeneratedAnalysisDraft")
    GeneratedAnalysisProfileLink = apps.get_model("reports", "GeneratedAnalysisProfileLink")
    BirthProfile = apps.get_model("charts", "BirthProfile")

    existing_profile_ids = set(BirthProfile.objects.values_list("id", flat=True))
    buffer = []
    for analysis in GeneratedAnalysisDraft.objects.only("id", "input_snapshot").iterator(chunk_size=500):
        for profile_id, role in profile_links_from_snapshot(analysis.input_snapshot):
            if profile_id not in existing_profile_ids:
                continue
            buffer.append(GeneratedAnalysisProfileLink(analysis_id=analysis.id, profile_id=profile_id, role=role))
            if len(buffer) >= 1000:
                GeneratedAnalysisProfileLink.objects.bulk_create(buffer, ignore_conflicts=True)
                buffer = []
    if buffer:
        GeneratedAnalysisProfileLink.objects.bulk_create(buffer, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_birthprofilerelationship_charts_rel_user_updated_idx_and_more'),
        ('reports', '0004_generatedanalysisdraft_parent_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAnalysisProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='primary', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='reports.generatedanalysisdraft')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_links', to='charts.birthprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'analysis'], name='reports_profile_analysis_idx'), models.Index(fields=['analysis', 'role'], name='reports_analysis_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('analysis', 'profile', 'role'), name='unique_analysis_profile_role')],
            },
        ),
        migrations.RunPython(backfill_profile_links, migrations.RunPython.noop),
    ]
