# Generated by Django 5.2.14 on 2026-06-13 07:15

from django.db import migrations, models


def input_summary_from_snapshot(snapshot, kind=""):
    if not isinstance(snapshot, dict):
        return {}

    def birth_summary(source):
        if not isinstance(source, dict):
            return {}
        return {
            key: source.get(key)
            for key in ("birth_date", "birth_time", "place_name", "place_id", "profile_id")
            if source.get(key) not in {None, ""}
        }

    if kind.startswith("compatibility"):
        summary = {}
        person_a = birth_summary(snapshot.get("person_a"))
        person_b = birth_summary(snapshot.get("person_b"))
        if person_a:
            summary["person_a"] = person_a
        if person_b:
            summary["person_b"] = person_b
        relationship = snapshot.get("relationship_context")
        if isinstance(relationship, dict):
            summary["relationship_context"] = {
                key: relationship.get(key)
                for key in ("role", "label", "relationship_id", "link_status", "profile_id", "related_profile_id")
                if relationship.get(key) not in {None, ""}
            }
        return summary

    summary = birth_summary(snapshot)
    for key in ("as_of_date", "as_of_time"):
        if snapshot.get(key) not in {None, ""}:
            summary[key] = snapshot.get(key)
    related_ids = snapshot.get("related_profile_ids")
    if isinstance(related_ids, list):
        summary["related_profile_ids"] = related_ids[:12]
    return summary


def backfill_input_summary(apps, schema_editor):
    GeneratedAnalysisDraft = apps.get_model("reports", "GeneratedAnalysisDraft")
    updates = []
    for record in GeneratedAnalysisDraft.objects.only("id", "kind", "input_snapshot").iterator(chunk_size=500):
        record.input_summary = input_summary_from_snapshot(record.input_snapshot, record.kind)
        updates.append(record)
        if len(updates) >= 500:
            GeneratedAnalysisDraft.objects.bulk_update(updates, ["input_summary"])
            updates = []
    if updates:
        GeneratedAnalysisDraft.objects.bulk_update(updates, ["input_summary"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_generatedanalysisprofilelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedanalysisdraft',
            name='input_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_input_summary, migrations.RunPython.noop),
    ]
