# Generated by Codex on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_generatedanalysisjob"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="generatedanalysisjob",
            index=models.Index(fields=["status", "created_at", "id"], name="reports_job_status_queue_idx"),
        ),
    ]
