import type { RuleDefinition, RuleId } from "./ruleTypes";

export const ruleDefinitions: RuleDefinition[] = [
  {
    id: "bphs.house.1",
    label: { ru: "Лагна как восходящий знак и основа чтения", en: "Lagna as rising sign and reading foundation" },
    domain: "house",
    appliesToEntityIds: ["house.1"],
    requiredCalculationIds: ["calc.varga.D1"],
    conditions: [{ type: "entity_present", entityId: "house.1" }],
    passageIds: ["passage.bphs.lagna.general"],
    status: "verified",
    interpretationPolicy: "conditional",
  },
  {
    id: "bphs.house.5",
    label: { ru: "Пятый дом как слой детей и разума", en: "Fifth house as children and intelligence layer" },
    domain: "house",
    appliesToEntityIds: ["house.5"],
    requiredCalculationIds: ["calc.varga.D1"],
    conditions: [{ type: "entity_present", entityId: "house.5" }],
    passageIds: [],
    status: "needs_source",
    interpretationPolicy: "context_only",
  },
  {
    id: "bphs.house.9",
    label: { ru: "Девятый дом как дхарма и благословение", en: "Ninth house as dharma and blessing" },
    domain: "house",
    appliesToEntityIds: ["house.9"],
    requiredCalculationIds: ["calc.varga.D1"],
    conditions: [{ type: "entity_present", entityId: "house.9" }],
    passageIds: [],
    status: "needs_source",
    interpretationPolicy: "context_only",
  },
  {
    id: "bphs.house.10",
    label: { ru: "Десятый дом как действие и статус", en: "Tenth house as action and status" },
    domain: "house",
    appliesToEntityIds: ["house.10"],
    requiredCalculationIds: ["calc.varga.D1"],
    conditions: [{ type: "entity_present", entityId: "house.10" }],
    passageIds: [],
    status: "needs_source",
    interpretationPolicy: "context_only",
  },
  {
    id: "bphs.graha.mo",
    label: { ru: "Луна как ум", en: "Moon as mind" },
    domain: "graha",
    appliesToEntityIds: ["graha.MO"],
    requiredCalculationIds: ["calc.planetPositions", "calc.nakshatras"],
    conditions: [{ type: "entity_present", entityId: "graha.MO" }],
    passageIds: ["passage.bphs.sun_moon.karakatva"],
    status: "verified",
    interpretationPolicy: "conditional",
  },
  {
    id: "bphs.graha.su",
    label: { ru: "Солнце как атма", en: "Sun as soul" },
    domain: "graha",
    appliesToEntityIds: ["graha.SU"],
    requiredCalculationIds: ["calc.planetPositions"],
    conditions: [{ type: "entity_present", entityId: "graha.SU" }],
    passageIds: ["passage.bphs.sun_moon.karakatva"],
    status: "verified",
    interpretationPolicy: "conditional",
  },
  {
    id: "jyotish.classical.varga.D1",
    label: { ru: "Раши входит в систему шестнадцати варг", en: "Rashi belongs to the sixteen-varga system" },
    domain: "varga",
    appliesToEntityIds: ["varga.D1"],
    requiredCalculationIds: ["calc.varga.D1"],
    conditions: [{ type: "calculation_available", calculationId: "calc.varga.D1" }],
    passageIds: ["passage.bphs.varga.sixteen.names", "passage.bphs.varga.uses"],
    status: "verified",
    interpretationPolicy: "context_only",
  },
  {
    id: "jyotish.classical.varga.D9",
    label: { ru: "Навамша входит в шестнадцать варг; супруг рассматривается через Навамшу", en: "Navamsha belongs to the sixteen vargas; spouse is considered through Navamsha" },
    domain: "varga",
    appliesToEntityIds: ["varga.D9"],
    requiredCalculationIds: ["calc.varga.D9"],
    conditions: [{ type: "calculation_available", calculationId: "calc.varga.D9" }],
    passageIds: ["passage.bphs.varga.sixteen.names", "passage.bphs.varga.uses"],
    status: "verified",
    interpretationPolicy: "context_only",
  },
  {
    id: "vimshottari.sequence",
    label: { ru: "Последовательность Вимшоттари", en: "Vimshottari sequence" },
    domain: "dasha",
    appliesToEntityIds: [],
    requiredCalculationIds: ["calc.vimshottari"],
    conditions: [{ type: "calculation_available", calculationId: "calc.vimshottari" }],
    passageIds: ["passage.vimshottari.sequence.general"],
    status: "verified",
    interpretationPolicy: "context_only",
  },
  {
    id: "bphs.aspect.graha_drishti.general_7th",
    label: { ru: "Граха-дришти: общий 7-й аспект", en: "Graha Drishti: general 7th aspect" },
    domain: "transit",
    appliesToEntityIds: ["graha.SU", "graha.MO", "graha.MA", "graha.ME", "graha.JU", "graha.VE", "graha.SA"],
    requiredCalculationIds: ["calc.grahaDrishti", "calc.transits"],
    conditions: [{ type: "calculation_available", calculationId: "calc.grahaDrishti" }],
    passageIds: ["passage.bphs.aspect.graha_drishti"],
    status: "verified",
    interpretationPolicy: "context_only",
    notes: "Technical aspect rule only; no interpretation, orbs, node aspects, or Rashi Drishti.",
  },
  {
    id: "bphs.aspect.graha_drishti.mars_special",
    label: { ru: "Граха-дришти: особые аспекты Марса", en: "Graha Drishti: Mars special aspects" },
    domain: "transit",
    appliesToEntityIds: ["graha.MA"],
    requiredCalculationIds: ["calc.grahaDrishti", "calc.transits"],
    conditions: [{ type: "calculation_available", calculationId: "calc.grahaDrishti" }],
    passageIds: ["passage.bphs.aspect.graha_drishti"],
    status: "verified",
    interpretationPolicy: "context_only",
    notes: "Technical aspect rule only; covers Mars 4th and 8th Graha Drishti.",
  },
  {
    id: "bphs.aspect.graha_drishti.jupiter_special",
    label: { ru: "Граха-дришти: особые аспекты Юпитера", en: "Graha Drishti: Jupiter special aspects" },
    domain: "transit",
    appliesToEntityIds: ["graha.JU"],
    requiredCalculationIds: ["calc.grahaDrishti", "calc.transits"],
    conditions: [{ type: "calculation_available", calculationId: "calc.grahaDrishti" }],
    passageIds: ["passage.bphs.aspect.graha_drishti"],
    status: "verified",
    interpretationPolicy: "context_only",
    notes: "Technical aspect rule only; covers Jupiter 5th and 9th Graha Drishti.",
  },
  {
    id: "bphs.aspect.graha_drishti.saturn_special",
    label: { ru: "Граха-дришти: особые аспекты Сатурна", en: "Graha Drishti: Saturn special aspects" },
    domain: "transit",
    appliesToEntityIds: ["graha.SA"],
    requiredCalculationIds: ["calc.grahaDrishti", "calc.transits"],
    conditions: [{ type: "calculation_available", calculationId: "calc.grahaDrishti" }],
    passageIds: ["passage.bphs.aspect.graha_drishti"],
    status: "verified",
    interpretationPolicy: "context_only",
    notes: "Technical aspect rule only; covers Saturn 3rd and 10th Graha Drishti.",
  },
];

const ruleMap = new Map(ruleDefinitions.map((rule) => [rule.id, rule]));

export function getRule(id: RuleId): RuleDefinition | null {
  return ruleMap.get(id) ?? null;
}

export function listRules(): RuleDefinition[] {
  return ruleDefinitions.filter((rule) => rule.status !== "disabled");
}
